# STRM Poller 配置示例文件
# 可将此文件复制为 config.yaml 放在配置目录中使用

# 服务器配置
server:
  host: "0.0.0.0"
  port: 35455  # 与代码和Docker配置保持一致
  debug: false

# 路径配置
paths:
  # 配置目录（容器内默认为 /config）
  config_path: "/config"
  # 源目录（包含 .strm 文件，容器内默认为 /src）
  src_path: "/src"
  # 目标目录（整理后的媒体文件，容器内默认为 /dst）
  dst_path: "/dst"

# 代理配置
proxy:
  enabled: false
  type: "http"  # http, https, socks5
  host: "localhost"
  port: 8080
  username: ""  # 可选
  password: ""  # 可选
  test_url: "https://api.themoviedb.org/3/configuration"

# 刮削源配置
scrapers:
  # 刮削源优先级顺序
  order: ["tmdb", "douban", "bangumi", "imdb", "tvdb"]
  
  # TMDB 配置
  tmdb:
    api_key: ""  # 必填，请从 TMDB 网站获取
    language: "zh-CN"
    timeout: 30
    retry_count: 3
  
  # 豆瓣配置
  douban:
    cookie: ""  # 必填，格式：dbcl2=xxx; ck=xxx
    timeout: 30
    retry_count: 3
  
  # Bangumi 配置
  bangumi:
    api_key: ""  # 必填，请从 Bangumi 网站获取
    timeout: 30
    retry_count: 3
  
  # IMDb 配置
  imdb:
    cookie: ""  # 可选
    timeout: 30
    retry_count: 3
  
  # TVDB 配置
  tvdb:
    api_key: ""  # 必填，请从 TVDB 网站获取
    timeout: 30
    retry_count: 3

# 系统配置
system:
  # 内存限制（MB）
  max_memory_mb: 1024
  # 最大工作线程数
  max_workers: 4
  # 任务超时时间（秒）
  task_timeout: 3600
  # 失败重试次数
  retry_count: 3
  # 重试延迟时间（秒）
  retry_delay: 3600
  
  # 用户配置
  puid: 1000
  pgid: 1000
  timezone: "Asia/Shanghai"

# 文件监控配置
watcher:
  # 文件事件防抖时间（秒）
  debounce_seconds: 1.0
  # 是否递归监控子目录
  recursive: true

# 文件整理配置
organize:
  # 整理策略：category（按类别）, type（按类型）, none（不整理）
  strategy: "category"
  # 重命名模板
  rename_template: "{title} ({year}){extension}"
  # 是否启用二级分类
  enable_subcategory: true
  # 二级分类映射
  subcategory_map:
    movie:
      Action: "动作"
      Comedy: "喜剧"
      Drama: "剧情"
      Horror: "恐怖"
      Sci-Fi: "科幻"
      Fantasy: "奇幻"
      Romance: "爱情"
    tv:
      Series: "剧集"
      Anime: "动画"
      Documentary: "纪录片"
      Reality: "真人秀"

# 通知配置
notification:
  # 微信企业机器人配置
  wechat:
    # 是否启用
    enabled: false
    # 企业机器人webhook地址
    webhook_url: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxx"
    # 通知事件范围，可选值：all, task_started, task_completed, task_failed, file_processed, file_failed, system_started, system_error
    events: ["task_started", "task_completed", "task_failed"]
  
  # Telegram配置
  telegram:
    # 是否启用
    enabled: false
    # Telegram机器人token
    bot_token: "xxx:xxx"
    # 聊天ID
    chat_id: "xxx"
    # 通知事件范围，可选值：all, task_started, task_completed, task_failed, file_processed, file_failed, system_started, system_error
    events: ["task_started", "task_completed", "task_failed"]

# 数据库配置
database:
  # SQLite 配置
  sqlite_path: "/config/strm-poller.db"

# 日志配置
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "/config/logs/strm-poller.log"
  max_size: 10485760  # 10MB
  backup_count: 5