# 此文件提供两种部署模式，请根据需要选择其中一种

# 模式1: Host网络模式（推荐）
# 使用方法: docker-compose -f docker-compose.yml up -d
# 注意: 在host模式下，应用程序会直接使用主机的35455端口
# 重要提示: 在host网络模式下，不需要设置ports端口映射，容器会直接使用主机网络栈
version: '3'
services:
  strm-poller:
    build: .
    image: tgszy/strm-poller:latest
    container_name: strm-poller
    restart: unless-stopped
    network_mode: host  # 使用host网络模式，直接使用主机网络栈
    volumes:
      - ./config:/config
      - ./src:/src:ro
      - ./dst:/dst
    environment:
      - TZ=Asia/Shanghai
      - MAX_MEMORY=1024
      - PROXY_ENABLED=false
      - LOG_LEVEL=INFO
      - DOCKER_ENV=true
      - CUSTOM_BIND_IP=0.0.0.0
    mem_limit: 1g
    memswap_limit: 1g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:35455/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

# 模式2: Bridge网络模式
# 如果需要使用bridge模式，请使用已有的docker-compose-bridge.yml文件
# docker-compose -f docker-compose-bridge.yml up -d
