# 简化桥接模式配置文件
# 仅支持本地IP:35455访问
# 使用方法: docker-compose -f docker-compose-bridge.yml up -d
version: '3'
services:
  strm-poller:
    build: .
    image: tgszy/strm-poller:latest
    container_name: strm-poller
    restart: unless-stopped
    ports:
      - "127.0.0.1:35455:35455"  # 仅绑定到本地回环地址
    volumes:
      - ./config:/config
      - ./src:/src:ro
      - ./dst:/dst
    environment:
      - TZ=Asia/Shanghai
      - MAX_MEMORY=1024
      - PROXY_ENABLED=false
      - LOG_LEVEL=INFO
      - DOCKER_ENV=true
      - CUSTOM_BIND_IP=0.0.0.0
    mem_limit: 1g
    memswap_limit: 1g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:35455/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
