# STRM Poller Docker Compose 配置文件
# 提供两种部署模式，请根据需要选择其中一种

version: '3.8'

services:
  strm-poller:
    image: ghcr.io/tgszy/strm-poller:latest
    container_name: strm-poller
    restart: unless-stopped
    
    # 模式1: Bridge网络模式（推荐用于大多数场景）
    ports:
      - "35455:35455"  # 映射到所有网络接口
    
    # 模式2: Host网络模式（仅用于需要直接使用主机网络的场景）
    # network_mode: host  # 取消注释使用host模式，此时不需要ports映射
    
    volumes:
      # 配置目录：存放配置文件、数据库和日志
      - ./config:/config
      # 源目录：存放待整理的.strm文件（建议只读）
      - ./src:/src:ro
      # 目标目录：存放整理后的媒体文件
      - ./dst:/dst
      
      # 可选：添加更多源目录或目标目录
      # - ./other_source:/src2:ro
      # - ./other_destination:/dst2
    
    environment:
      # 基本配置
      - TZ=Asia/Shanghai
      - MAX_MEMORY=1024
      - LOG_LEVEL=INFO
      
      # 代理配置（如需使用）
      - PROXY_ENABLED=false
      # - PROXY_URL=http://proxy.example.com:8080
      # - PROXY_TYPE=http
      
      # 通知配置（可选）
      # - NOTIFY_WECHAT_ENABLED=false
      # - NOTIFY_TELEGRAM_ENABLED=false
      
      # Docker环境标识
      - DOCKER_ENV=true
    
    # 资源限制
    mem_limit: 1g
    memswap_limit: 1g
    
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:35455/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 日志配置
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
