# 此文件提供两种部署模式，请根据需要选择其中一种

# 模式1: Host网络模式（推荐）
# 使用方法: docker-compose -f docker-compose.yml up -d
# 注意: 在host模式下，应用程序会直接使用主机的35455端口
version: '3'
services:
  strm-poller:
    build: .
    image: tgszy/strm-poller:latest
    container_name: strm-poller
    restart: unless-stopped
    network_mode: host  # 使用host网络模式，直接使用主机网络栈
    volumes:
      - ./config:/config
      - ./src_files:/src:ro
      - ./dst_files:/dst
    environment:
      - TZ=Asia/Shanghai
      - MAX_MEMORY=1024
      - PROXY_ENABLED=false
      - LOG_LEVEL=INFO
      - DOCKER_ENV=true
      - CUSTOM_BIND_IP=0.0.0.0
    mem_limit: 1g
    memswap_limit: 1g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:35455/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

# 模式2: Bridge网络模式
# 如果需要使用bridge模式，请将以下内容复制到一个新文件docker-compose-bridge.yml中使用
# docker-compose -f docker-compose-bridge.yml up -d
#
# version: '3'
# services:
#   strm-poller:
#     build: .
#     image: tgszy/strm-poller:latest
#     container_name: strm-poller
#     restart: unless-stopped
#     networks:
#       - strm_network
#     ports:
#       - "35455:35455"  # 确保与代码中使用的35455端口保持一致
#     volumes:
#       - ./config:/config
#       - ./src_files:/src:ro
#       - ./dst_files:/dst
#     environment:
#       - TZ=Asia/Shanghai
#       - MAX_MEMORY=1024
#       - PROXY_ENABLED=false
#       - LOG_LEVEL=INFO
#       - DOCKER_ENV=true
#       - CUSTOM_BIND_IP=0.0.0.0
#     mem_limit: 1g
#     memswap_limit: 1g
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:35455/api/health"]
#       interval: 30s
#       timeout: 10s
#       retries: 3
#       start_period: 40s
#     logging:
#       driver: json-file
#       options:
#         max-size: "10m"
#         max-file: "3"
#
# networks:
#   strm_network:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.18.0.0/16
#           gateway: 172.18.0.1
#     # 优化网络性能的额外参数
#     driver_opts:
#       com.docker.network.bridge.enable_icc: "true"  # 启用容器间通信
#       com.docker.network.bridge.enable_ip_masquerade: "true"  # 启用IP伪装
#       com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"  # 绑定到所有接口
