services:
  strm-poller:
    # 使用本地构建的镜像替代GitHub Container Registry
    build: .
    # 如果需要使用其他镜像源，可以取消下面这行注释并修改为相应的镜像地址
    # image: tgszy/strm-poller:latest
    container_name: strm-poller
    restart: unless-stopped
    # 支持桥接模式，默认使用bridge网络
    # 注释掉host网络模式，改为使用默认的bridge网络并正确映射端口
    # network_mode: "host"
    ports:
      - "35455:35455"  # 默认端口映射，用户可以修改冒号前的数字来自定义外部端口
    # 网络配置，确保容器可以被主机网络访问
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "docker.for.win.localhost:host-gateway"  # Windows Docker兼容性
    volumes:
      # 配置目录：包含数据库、配置文件和日志
      # Windows路径示例: - C:\path\to\config:/config
      - ./config:/config
      # 源目录：包含.strm文件的目录，建议设置为只读
      # 请根据您的环境修改下面的路径
      # Windows路径示例: - C:\path\to\src:/src:ro
      - ./src_files:/src:ro
      # 目标目录：整理后的媒体文件将存放在这里
      # 请根据您的环境修改下面的路径
      # Windows路径示例: - C:\path\to\dst:/dst
      - ./dst_files:/dst
      # 可自定义添加更多源目录和目标目录映射
      # 例如：
      # - ./other_source:/src2:ro
      # - ./other_destination:/dst2
    environment:
      # 用户权限设置
      - PUID=1000
      - PGID=1000
      # 时区设置
      - TZ=Asia/Shanghai
      # 内存限制 (MB)
      - MAX_MEMORY=1024
      # 代理设置
      - PROXY_ENABLED=false
      - PROXY_URL=
      # 日志级别
      - LOG_LEVEL=INFO
    # 容器内存限制
    mem_limit: 1g
    memswap_limit: 1g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:35455/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=false"

  # 可选：自动更新容器
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 86400 --label-enable --cleanup
    labels:
      - "com.centurylinklabs.watchtower.enable=false"