version: '3.8'

services:
  strm-poller:
    image: tgszy/strm-poller:latest
    container_name: strm-poller
    ports:
      - "8080:8080"
    volumes:
      - ./media:/media
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=INFO
      - PROXY_ENABLED=true
      - MEMORY_LIMIT_MB=1024
      - ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.tgszy.strm-poller.description=STRM Poller - 智能媒体整理工具"
      - "com.tgszy.strm-poller.version=latest"
      - "com.tgszy.strm-poller.maintainer=tgszy"

  # 可选：Watchtower自动更新
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600  # 每小时检查一次
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_REVIVE_STOPPED=true
    command: --cleanup strm-poller
    restart: unless-stopped